import type { Metadata } from 'next';
import { Geist, Geist_Mono, Instrument_Sans } from 'next/font/google';

import { cn } from "@/lib/utils";
import './globals.css';

const instrumentSansHeading = Instrument_Sans({subsets:['latin'],variable:'--font-heading'});

const geistSans = Geist({
  variable: '--font-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, instrumentSansHeading.variable)}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  )
}
